DECLARE
   CURSOR cur_tables IS
   SELECT table_name
   FROM   user_tables
   WHERE  table_name like 'EBA_%';


BEGIN
   FOR rec_tables IN cur_tables
   LOOP
      BEGIN
         EXECUTE IMMEDIATE 'DROP TABLE '||rec_tables.table_name ||' cascade constraints';
      EXCEPTION
         WHEN OTHERS THEN
           IF SQLCODE != -942 THEN
              RAISE;
          END IF;
      END;
   END LOOP;
END;
/
CREATE TABLE  EBA_DHB 
   (	DHB_ID NUMBER NOT NULL ENABLE, 
	ORG_CODE VARCHAR2(5) NOT NULL ENABLE, 
	DHB_SHORTNAME VARCHAR2(30) NOT NULL ENABLE, 
	DHB_LONGNAME VARCHAR2(30) NOT NULL ENABLE, 
	CREATED DATE, 
	CREATED_BY VARCHAR2(50), 
	UPDATED DATE, 
	UPDATED_BY VARCHAR2(50), 
	 CONSTRAINT EBA_DHB_PK PRIMARY KEY (DHB_ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_ASSETPERSONNEL 
   (	ASSETPERSONNEL_ID NUMBER NOT NULL ENABLE, 
	DHB_ID NUMBER NOT NULL ENABLE, 
	FIRSTNAME VARCHAR2(30) NOT NULL ENABLE, 
	LASTNAME VARCHAR2(30), 
	SERVICEMANAGER VARCHAR2(1) NOT NULL ENABLE, 
	BUSINESSMANAGER VARCHAR2(1) NOT NULL ENABLE, 
	BUDGETHOLDER VARCHAR2(1) NOT NULL ENABLE, 
	SIGNATORY VARCHAR2(1) NOT NULL ENABLE, 
	CREATED DATE, 
	CREATED_BY VARCHAR2(50), 
	UPDATED DATE, 
	UPDATED_BY VARCHAR2(50), 
	ASSIGNED_TO VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	ENDORSED_BY VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT EBA_ASSETPERSONNEL_PK PRIMARY KEY (ASSETPERSONNEL_ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_IMPORTANCE_CODES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	IMPORTANCE_TEXT VARCHAR2(255) NOT NULL ENABLE, 
	IMPORTANCE_COLOR VARCHAR2(30), 
	DISPLAY_SEQUENCE NUMBER NOT NULL ENABLE, 
	IMPORTANCE_WEIGHT NUMBER NOT NULL ENABLE, 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_DECISION_IMP_CD_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_PROJECTS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	PROJECT_NAME VARCHAR2(255) NOT NULL ENABLE, 
	PROJECT_OWNER VARCHAR2(255), 
	CONTRIBUTOR_1 VARCHAR2(255), 
	CONTRIBUTOR_2 VARCHAR2(255), 
	CONTRIBUTOR_3 VARCHAR2(255), 
	CONTRIBUTOR_4 VARCHAR2(255), 
	PROJECT_DESCRIPTION VARCHAR2(4000), 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_DECISION_PROJECTS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_PROJ_LIFECYCLE 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	LIFECYCLE_STAGE VARCHAR2(255) NOT NULL ENABLE, 
	DISPLAY_SEQUENCE NUMBER, 
	STAGE_DESCRIPTION VARCHAR2(4000), 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_DECISION_PRJ_LC_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_STATUS_CODES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER NOT NULL ENABLE, 
	STATUS_TEXT VARCHAR2(255) NOT NULL ENABLE, 
	STATUS_COLOR VARCHAR2(30), 
	IS_OPEN_YN VARCHAR2(1), 
	DISPLAY_SEQUENCE NUMBER NOT NULL ENABLE, 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_DECISION_ST_CD_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_TYPES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	DISPLAY_SEQUENCE NUMBER, 
	DECISION_TYPE VARCHAR2(255) NOT NULL ENABLE, 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_DECISION_TYPES_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISIONS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER NOT NULL ENABLE, 
	ROW_KEY VARCHAR2(30), 
	DECISION VARCHAR2(255) NOT NULL ENABLE, 
	DECISION_DETAILS VARCHAR2(4000), 
	PROJECT_ID NUMBER, 
	DECISION_TYPE_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	STATUS_ID NUMBER, 
	IMPORTANCE_ID NUMBER, 
	TAGS VARCHAR2(4000), 
	WHY_REQUESTING VARCHAR2(4000), 
	IS_DELETED VARCHAR2(1) NOT NULL ENABLE, 
	IS_LOCKED VARCHAR2(1) NOT NULL ENABLE, 
	INTERESTED_PARTIES_ONLY VARCHAR2(1), 
	REQUESTING_PARTY VARCHAR2(255), 
	INTERESTED_PARTY_1 VARCHAR2(255), 
	INTERESTED_PARTY_2 VARCHAR2(255), 
	INTERESTED_PARTY_3 VARCHAR2(255), 
	INTERESTED_PARTY_4 VARCHAR2(255), 
	INTERESTED_PARTY_5 VARCHAR2(255), 
	INTERESTED_PARTY_6 VARCHAR2(255), 
	INTERESTED_PARTY_7 VARCHAR2(255), 
	INTERESTED_PARTY_8 VARCHAR2(255), 
	REQUESTED_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	DECISION_AUTHORITY VARCHAR2(255), 
	DECISION_COMMENTS VARCHAR2(4000), 
	DECISION_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	DECISION_FORUM VARCHAR2(255), 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_DECISIONS_DEL_CK CHECK (is_deleted in ('Y','N')) ENABLE, 
	 CONSTRAINT EBA_DECISIONS_LOCK_CK CHECK (is_locked in ('Y','N')) ENABLE, 
	 CONSTRAINT EBA_DECISIONS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_ACCESS_LEVELS 
   (	ID NUMBER NOT NULL ENABLE, 
	ACCESS_LEVEL VARCHAR2(30) NOT NULL ENABLE, 
	ROW_VERSION NUMBER, 
	 CONSTRAINT EBA_DM_ACC_LVL_ACC_LVL_CK CHECK (access_level in (
                                                    'Administrator',
                                                    'Contributor',
                                                    'Reader' )) ENABLE, 
	 CONSTRAINT EBA_DM_ACCESS_LEVELS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_CLICKS 
   (	ID NUMBER, 
	VIEW_ID NUMBER, 
	APP_USERNAME VARCHAR2(255), 
	VIEW_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	APP_SESSION VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_ERRORS 
   (	ID NUMBER NOT NULL ENABLE, 
	ERR_TIME TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT localtimestamp NOT NULL ENABLE, 
	APP_ID NUMBER, 
	APP_PAGE_ID NUMBER, 
	APP_USER VARCHAR2(512), 
	USER_AGENT VARCHAR2(4000), 
	IP_ADDRESS VARCHAR2(512), 
	IP_ADDRESS2 VARCHAR2(512), 
	MESSAGE VARCHAR2(4000), 
	PAGE_ITEM_NAME VARCHAR2(255), 
	REGION_ID NUMBER, 
	COLUMN_ALIAS VARCHAR2(255), 
	ROW_NUM NUMBER, 
	APEX_ERROR_CODE VARCHAR2(255), 
	ORA_SQLCODE NUMBER, 
	ORA_SQLERRM VARCHAR2(4000), 
	ERROR_BACKTRACE VARCHAR2(4000), 
	 CONSTRAINT EBA_DECISION_ERRORS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_ERROR_LOOKUP 
   (	CONSTRAINT_NAME VARCHAR2(30) NOT NULL ENABLE, 
	MESSAGE VARCHAR2(4000) NOT NULL ENABLE, 
	LANGUAGE_CODE VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT EBA_DECISION_ERROR_LOOKUP_PK PRIMARY KEY (CONSTRAINT_NAME)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_FILES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	DECISION_ID NUMBER, 
	PROJECT_ID NUMBER, 
	FILENAME VARCHAR2(4000), 
	FILE_MIMETYPE VARCHAR2(512), 
	FILE_CHARSET VARCHAR2(512), 
	FILE_BLOB BLOB, 
	FILE_COMMENTS VARCHAR2(4000), 
	TAGS VARCHAR2(4000), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DECISION_FILES_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_HISTORY 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	DECISION_ID NUMBER, 
	DECISION_ROWKEY VARCHAR2(30), 
	COLUMN_NAME VARCHAR2(60) NOT NULL ENABLE, 
	OLD_VALUE VARCHAR2(4000), 
	NEW_VALUE VARCHAR2(4000), 
	CHANGE_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CHANGED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DECISION_HISTORY_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_LINKS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER NOT NULL ENABLE, 
	DECISION_ID NUMBER NOT NULL ENABLE, 
	PROJECT_ID NUMBER, 
	LINK_TARGET VARCHAR2(4000), 
	LINK_TEXT VARCHAR2(255), 
	LINK_COMMENTS VARCHAR2(4000), 
	TAGS VARCHAR2(4000), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DECISION_LINKS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_NOTES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER NOT NULL ENABLE, 
	DECISION_ID NUMBER NOT NULL ENABLE, 
	NOTE CLOB, 
	TAGS VARCHAR2(4000), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DECISION_NOTES_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_NOTIFICATIONS 
   (	ID NUMBER NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER, 
	NOTIFICATION_NAME VARCHAR2(255) NOT NULL ENABLE, 
	NOTIFICATION_DESCRIPTION VARCHAR2(4000), 
	NOTIFICATION_TYPE VARCHAR2(30) NOT NULL ENABLE, 
	DISPLAY_SEQUENCE NUMBER, 
	DISPLAY_FROM TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	DISPLAY_UNTIL TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255) NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255) NOT NULL ENABLE, 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_DECISION_NOTE_TP_CC CHECK (notification_type in ('RED','YELLOW')) ENABLE, 
	 CONSTRAINT EBA_DECISION_NOTE_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_PREFERENCES 
   (	ID NUMBER NOT NULL ENABLE, 
	PREFERENCE_NAME VARCHAR2(255) NOT NULL ENABLE, 
	PREFERENCE_VALUE VARCHAR2(255) NOT NULL ENABLE, 
	CREATED_BY VARCHAR2(255) NOT NULL ENABLE, 
	CREATED_ON TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED_ON TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_DM_PREFS_PREFNAME_CK CHECK (upper(preference_name)=preference_name) ENABLE, 
	 CONSTRAINT EBA_DECISION_PREFERENCES_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_TAGS 
   (	ID NUMBER, 
	TAG VARCHAR2(255) NOT NULL ENABLE, 
	CONTENT_ID NUMBER, 
	CONTENT_TYPE VARCHAR2(30), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DECISION_TAGS_CK CHECK (content_type in ('DECISION','NOTES','FILE')) ENABLE, 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_TAGS_SUM 
   (	TAG VARCHAR2(255), 
	TAG_COUNT NUMBER, 
	 CONSTRAINT EBA_DECISION_TAGS_SUM_PK PRIMARY KEY (TAG)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_TAGS_TYPE_SUM 
   (	TAG VARCHAR2(255), 
	CONTENT_TYPE VARCHAR2(30), 
	TAG_COUNT NUMBER, 
	 CONSTRAINT EBA_DECISION_TAGS_TYPE_SUM_PK PRIMARY KEY (TAG, CONTENT_TYPE)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_TZ_PREF 
   (	ID NUMBER NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER(*,0), 
	USERID VARCHAR2(255) NOT NULL ENABLE, 
	TIMEZONE_PREFERENCE VARCHAR2(255) NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DECISION_TZ_PREF_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DECISION_USERS 
   (	ID NUMBER NOT NULL ENABLE, 
	USERNAME VARCHAR2(255) NOT NULL ENABLE, 
	ACCESS_LEVEL_ID NUMBER NOT NULL ENABLE, 
	ACCOUNT_LOCKED VARCHAR2(1) NOT NULL ENABLE, 
	ROW_VERSION NUMBER, 
	CREATED_BY VARCHAR2(255) NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_DM_USERS_USERNAME_CK CHECK (upper(username)=username) ENABLE, 
	 CONSTRAINT EBA_DM_USERS_ACC_LOCKED_CK CHECK (account_locked in ('Y','N')) ENABLE, 
	 CONSTRAINT EBA_DECISION_USERS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DELIVERY_CODES 
   (	LOCATION_TYPE VARCHAR2(20), 
	LOCATION_DESCRIPTION VARCHAR2(100), 
	 CONSTRAINT EBA_DELIVERY_CODES_PK PRIMARY KEY (LOCATION_TYPE)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_CHART_DEPT 
   (	DEPTNO NUMBER(2,0) NOT NULL ENABLE, 
	DNAME VARCHAR2(14), 
	LOC VARCHAR2(13), 
	 CONSTRAINT EBA_DEMO_CHART_DEPT_PK PRIMARY KEY (DEPTNO)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_CHART_EMP 
   (	EMPNO NUMBER(4,0) NOT NULL ENABLE, 
	ENAME VARCHAR2(10), 
	JOB VARCHAR2(9), 
	MGR NUMBER(4,0), 
	HIREDATE DATE, 
	SAL NUMBER(7,2), 
	COMM NUMBER(7,2), 
	DEPTNO NUMBER(2,0), 
	 CONSTRAINT EBA_DEMO_CHART_EMP_PK PRIMARY KEY (EMPNO)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_CHART_POPULATION 
   (	ID NUMBER NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER, 
	STATE_NAME VARCHAR2(100), 
	STATE_CODE VARCHAR2(2), 
	POPULATION NUMBER, 
	REGION NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DEMO_CHART_POP_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_CHART_PROJECTS 
   (	ID NUMBER NOT NULL ENABLE, 
	PROJECT VARCHAR2(30) NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DEMO_CHARTS_PROJ_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_CHART_STOCKS 
   (	ID NUMBER NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER, 
	STOCK_CODE VARCHAR2(4), 
	STOCK_NAME VARCHAR2(130), 
	PRICING_DATE DATE, 
	OPENING_VAL NUMBER, 
	HIGH NUMBER, 
	LOW NUMBER, 
	CLOSING_VAL NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DEMO_CHART_STOCKS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_CHART_TASKS 
   (	ID NUMBER NOT NULL ENABLE, 
	PROJECT NUMBER, 
	PARENT_TASK NUMBER, 
	TASK_NAME VARCHAR2(255), 
	ROW_VERSION_NUMBER NUMBER, 
	START_DATE DATE, 
	END_DATE DATE, 
	STATUS VARCHAR2(30), 
	ASSIGNED_TO VARCHAR2(30), 
	COST NUMBER, 
	BUDGET NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_DEMO_CHART_TASKS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_IR_DEPT 
   (	DEPTNO NUMBER(2,0) NOT NULL ENABLE, 
	DNAME VARCHAR2(14), 
	LOC VARCHAR2(13), 
	 CONSTRAINT EBA_DEMO_IR_DEPT_PK PRIMARY KEY (DEPTNO)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_IR_EMP 
   (	EMPNO NUMBER(4,0) NOT NULL ENABLE, 
	ENAME VARCHAR2(10), 
	JOB VARCHAR2(9), 
	MGR NUMBER(4,0), 
	HIREDATE DATE, 
	SAL NUMBER(7,0), 
	COMM NUMBER(7,0), 
	DEPTNO NUMBER(2,0), 
	 CONSTRAINT EBA_DEMO_IR_EMP_PK PRIMARY KEY (EMPNO)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_IR_PROJECTS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	PROJECT VARCHAR2(30), 
	TASK_NAME VARCHAR2(255), 
	START_DATE DATE, 
	END_DATE DATE, 
	STATUS VARCHAR2(30), 
	ASSIGNED_TO VARCHAR2(30), 
	COST NUMBER, 
	BUDGET NUMBER
   )
/
CREATE TABLE  EBA_DEMO_MD_DEPT 
   (	DEPTNO NUMBER, 
	DNAME VARCHAR2(50), 
	LOC VARCHAR2(50), 
	 PRIMARY KEY (DEPTNO)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DEMO_MD_EMP 
   (	EMPNO NUMBER NOT NULL ENABLE, 
	ENAME VARCHAR2(50), 
	JOB VARCHAR2(50), 
	MGR NUMBER, 
	HIREDATE DATE, 
	SAL NUMBER(7,2), 
	COMM NUMBER(7,2), 
	DEPTNO NUMBER, 
	 PRIMARY KEY (EMPNO)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_DIVISION 
   (	DIVISION_ID NUMBER, 
	DESCRIPTION VARCHAR2(100), 
	 CONSTRAINT EBA_DIVISION_PK PRIMARY KEY (DIVISION_ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_ENDORSEMENT 
   (	ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT EBA_ENDORSEMENT_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_ITEMS 
   (	ITEM_ID NUMBER NOT NULL ENABLE, 
	ITEM_NAME VARCHAR2(100) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(100) NOT NULL ENABLE, 
	CREATED DATE, 
	CREATED_BY VARCHAR2(25), 
	UPDATED DATE, 
	UPDATED_BY VARCHAR2(25), 
	 CONSTRAINT EBA_ITEM PRIMARY KEY (ITEM_ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_LOCATION 
   (	LOCATION_ID NUMBER NOT NULL ENABLE, 
	LOCATION_CODE VARCHAR2(25), 
	RC_CODE VARCHAR2(25) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(50), 
	 CONSTRAINT EBA_LOCATION_CON PRIMARY KEY (LOCATION_ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_CATALOGUE 
   (	DESCRIPTION VARCHAR2(1000), 
	ITEM_NO VARCHAR2(100), 
	BRAND VARCHAR2(100), 
	MANUFACTURER VARCHAR2(100), 
	LEAD_TIME VARCHAR2(100), 
	WARRANTY VARCHAR2(100), 
	PRICE VARCHAR2(100), 
	USERID VARCHAR2(30)
   )
/
CREATE TABLE  EBA_PROJ_COLOR_CODES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	COLOR_NAME VARCHAR2(255) NOT NULL ENABLE, 
	COLOR_CODE VARCHAR2(10) DEFAULT '#F2F2F2' NOT NULL ENABLE, 
	SPRITE_URL VARCHAR2(255), 
	SPRITE_POSITION_X NUMBER DEFAULT 0, 
	SPRITE_POSITION_Y NUMBER DEFAULT 0, 
	DISPLAY_SEQUENCE NUMBER, 
	IS_ACTIVE_YN VARCHAR2(1), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_ERRORS 
   (	ID NUMBER NOT NULL ENABLE, 
	ERR_TIME TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT localtimestamp NOT NULL ENABLE, 
	APP_ID NUMBER, 
	APP_PAGE_ID NUMBER, 
	APP_USER VARCHAR2(512), 
	USER_AGENT VARCHAR2(4000), 
	IP_ADDRESS VARCHAR2(512), 
	IP_ADDRESS2 VARCHAR2(512), 
	MESSAGE VARCHAR2(4000), 
	PAGE_ITEM_NAME VARCHAR2(255), 
	REGION_ID NUMBER, 
	COLUMN_ALIAS VARCHAR2(255), 
	ROW_NUM NUMBER, 
	APEX_ERROR_CODE VARCHAR2(255), 
	ORA_SQLCODE NUMBER, 
	ORA_SQLERRM VARCHAR2(4000), 
	ERROR_BACKTRACE VARCHAR2(4000), 
	 CONSTRAINT EBA_PROJ_ERRORS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_ERROR_LOOKUP 
   (	CONSTRAINT_NAME VARCHAR2(30) NOT NULL ENABLE, 
	MESSAGE VARCHAR2(4000) NOT NULL ENABLE, 
	LANGUAGE_CODE VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT EBA_PROJ_ERROR_LOOKUP_PK PRIMARY KEY (CONSTRAINT_NAME)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_FLEX_PAGE_MAP 
   (	ID NUMBER, 
	FLEX_TABLE VARCHAR2(128) NOT NULL ENABLE, 
	PAGE_ID NUMBER NOT NULL ENABLE, 
	REGION_ID NUMBER NOT NULL ENABLE, 
	FLEX_COLUMN_PREFIX VARCHAR2(30) NOT NULL ENABLE, 
	REGION_TYPE VARCHAR2(30) NOT NULL ENABLE, 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_FLEX_REGISTRY 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER(*,0), 
	FLEXIBLE_TABLE VARCHAR2(128) NOT NULL ENABLE, 
	FLEXIBLE_COLUMN VARCHAR2(128) NOT NULL ENABLE, 
	FRIENDLY_NAME VARCHAR2(128), 
	ASSIGNED_YN VARCHAR2(1) NOT NULL ENABLE, 
	ACTIVE_YN VARCHAR2(1) NOT NULL ENABLE, 
	REPORT_CSS_CLASS VARCHAR2(128) NOT NULL ENABLE, 
	TABLE_PREFIX VARCHAR2(30) NOT NULL ENABLE, 
	DISPLAY_NAME_SING VARCHAR2(128) NOT NULL ENABLE, 
	DISPLAY_NAME_PLRL VARCHAR2(128) NOT NULL ENABLE, 
	FORM_LABEL_TEXT VARCHAR2(255) NOT NULL ENABLE, 
	REPORT_LABEL_TEXT VARCHAR2(255), 
	IS_REQUIRED_YN VARCHAR2(1) NOT NULL ENABLE, 
	IS_DISPLAYED_ON_IR VARCHAR2(1) NOT NULL ENABLE, 
	LABEL_TEMPLATE_ID NUMBER NOT NULL ENABLE, 
	DISPLAY_AS VARCHAR2(255) NOT NULL ENABLE, 
	WIDTH NUMBER NOT NULL ENABLE, 
	MAX_WIDTH NUMBER NOT NULL ENABLE, 
	HEIGHT NUMBER NOT NULL ENABLE, 
	FORMAT_MASK VARCHAR2(30), 
	LABEL_ALIGNMENT VARCHAR2(30), 
	HELP_TEXT VARCHAR2(4000), 
	LOV_TYPE VARCHAR2(30), 
	LOV_SQL_QUERY CLOB, 
	LOV_DISPLAY_COL VARCHAR2(30), 
	LOV_RETURN_COL VARCHAR2(30), 
	DEFAULT_VALUE VARCHAR2(4000), 
	RPT_HDR_ALIGNMENT VARCHAR2(30), 
	CONDITION_TYPE VARCHAR2(255), 
	CONDITION1 VARCHAR2(4000), 
	CONDITION2 VARCHAR2(4000), 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_PROJ_FLEX_CHK_DSPLY_AS_VAL CHECK (display_as in ('SELECT_LIST','TEXT','TEXTAREA','DATE','NUMBER')) ENABLE, 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_FLEX_STATIC_LOVS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER(*,0), 
	FLEX_TABLE VARCHAR2(128) NOT NULL ENABLE, 
	FLEX_COLUMN VARCHAR2(128) NOT NULL ENABLE, 
	DISPLAY_SEQUENCE NUMBER, 
	DISPLAY_VALUE VARCHAR2(255) NOT NULL ENABLE, 
	RETURN_VALUE VARCHAR2(4000) NOT NULL ENABLE, 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_GLCODES 
   (	CODE_COMBINATION_ID VARCHAR2(10), 
	CHART_OF_ACCOUNTS_ID VARCHAR2(10), 
	CODE_COMBINATION VARCHAR2(25), 
	COMPANY VARCHAR2(2), 
	SERVICE VARCHAR2(3), 
	DEPARTMENT VARCHAR2(4), 
	ACCOUNT VARCHAR2(4), 
	SUBACCOUNT VARCHAR2(5), 
	COMPANY_DESCRIPTION VARCHAR2(250), 
	SERVICE_DESCRIPTION VARCHAR2(250), 
	DEPARTMENT_DESCRIPTION VARCHAR2(250), 
	ACCOUNT_DESCRIPTION VARCHAR2(250), 
	SUBACCOUNT_DESCRIPTION VARCHAR2(250), 
	CODE_DESCRIPTION VARCHAR2(250), 
	RC_CODE VARCHAR2(15), 
	 CONSTRAINT EBA_PROJ_GLCODES_PK PRIMARY KEY (CODE_COMBINATION_ID)
  USING INDEX (CREATE UNIQUE INDEX  EBA_PROJ_GLCODES_IDX1 ON  EBA_PROJ_GLCODES (CODE_COMBINATION_ID) 
  )  ENABLE, 
	 CONSTRAINT EBA_PROJ_GLCODES_UK UNIQUE (CODE_COMBINATION)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_HELP_PAGE 
   (	ID NUMBER NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER(*,0), 
	LANGUAGE_CODE VARCHAR2(30), 
	APPLICATION_NAME VARCHAR2(255), 
	SPRITE VARCHAR2(1000), 
	ALTERNATIVE_IMAGE VARCHAR2(1000), 
	SHOW_APP_VERSION_YN VARCHAR2(1), 
	SHOW_PAGE_COUNT_YN VARCHAR2(1), 
	USE_APP_TITLE_YN VARCHAR2(1), 
	SHOW_ICON VARCHAR2(255), 
	SUPPORT_LINK VARCHAR2(1000), 
	SUPPORT_LINK_TEXT VARCHAR2(1000), 
	ADDITIONAL_HELP_LINK VARCHAR2(1000), 
	VENDOR VARCHAR2(1000), 
	TWITTER VARCHAR2(1000), 
	FACEBOOK VARCHAR2(1000), 
	LINKEDIN VARCHAR2(1000), 
	WEBSITE VARCHAR2(1000), 
	ATTR_LABEL_01 VARCHAR2(255), 
	ATTR_VALUE_01 VARCHAR2(1000), 
	ATTR_LABEL_02 VARCHAR2(255), 
	ATTR_VALUE_02 VARCHAR2(1000), 
	ATTR_LABEL_03 VARCHAR2(255), 
	ATTR_VALUE_03 VARCHAR2(1000), 
	ATTR_LABEL_04 VARCHAR2(255), 
	ATTR_VALUE_04 VARCHAR2(1000), 
	ATTR_LABEL_05 VARCHAR2(255), 
	ATTR_VALUE_05 VARCHAR2(1000), 
	ATTR_LABEL_06 VARCHAR2(255), 
	ATTR_VALUE_06 VARCHAR2(1000), 
	ATTR_LABEL_07 VARCHAR2(255), 
	ATTR_VALUE_07 VARCHAR2(1000), 
	ATTR_LABEL_08 VARCHAR2(255), 
	ATTR_VALUE_08 VARCHAR2(1000), 
	ABOUT_APP CLOB, 
	GETTING_STARTED CLOB, 
	QUICK_START CLOB, 
	SUPPORT CLOB, 
	PUBLIC_HELP CLOB, 
	FEATURES CLOB, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_PROJ_HELP_PAGE_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_HISTORY 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	COMPONENT_ID NUMBER, 
	COMPONENT_ROWKEY VARCHAR2(30), 
	TABLE_NAME VARCHAR2(60) DEFAULT 'STATUS' NOT NULL ENABLE, 
	COLUMN_NAME VARCHAR2(60) NOT NULL ENABLE, 
	OLD_VALUE VARCHAR2(4000), 
	NEW_VALUE VARCHAR2(4000), 
	CHANGE_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CHANGED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_PROJ_HISTORY_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_LOAD_CATALOGUE 
   (	DESCRIPTION VARCHAR2(4000), 
	ITEM_NO VARCHAR2(100), 
	BRAND VARCHAR2(100), 
	MANUFACTURER VARCHAR2(100), 
	LEAD_TIME VARCHAR2(100), 
	WARRANTY VARCHAR2(100), 
	PRICE VARCHAR2(100), 
	USERID VARCHAR2(30), 
	ID NUMBER NOT NULL ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_CATS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	CATEGORY VARCHAR2(100), 
	DISPLAY_SEQUENCE NUMBER, 
	IS_ACTIVE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	REQUESTOR VARCHAR2(50), 
	RC_CODE VARCHAR2(50), 
	SERVICE VARCHAR2(50), 
	DIVISION VARCHAR2(50), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_CODES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	STATUS_SHORT_DESC VARCHAR2(255) NOT NULL ENABLE, 
	IS_CLOSED_STATUS VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	COLOR_CODE_ID NUMBER, 
	IS_ACTIVE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	IS_DESIRABLE_YN VARCHAR2(1), 
	DISPLAY_SEQUENCE NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	CAT_ID NUMBER, 
	PARENT_PROJECT_ID NUMBER, 
	ROW_KEY VARCHAR2(30), 
	PROJECT VARCHAR2(200), 
	DESCRIPTION VARCHAR2(4000), 
	PROJECT_CUSTOMER VARCHAR2(255), 
	LOCKDOWN_TO_OWNERS_YN VARCHAR2(1), 
	PROJECT_OWNER VARCHAR2(255), 
	PROJECT_STATUS NUMBER, 
	TAGS VARCHAR2(4000), 
	NEXT_MILESTONE_NAME VARCHAR2(100), 
	NEXT_MILESTONE_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	GOAL VARCHAR2(4000), 
	WHAT_IS_SUCCESS VARCHAR2(4000), 
	URL VARCHAR2(4000), 
	INCLUDE_BY_DEFAULT_YN VARCHAR2(1), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	FINANCIAL_YEAR VARCHAR2(50), 
	BUDGETED_COST NUMBER, 
	APPROVED_COST NUMBER, 
	CER_NO_PROJECT_ID VARCHAR2(50), 
	AC_APPROVAL_DATE DATE, 
	AVOIDANCE_COST NUMBER, 
	PICK_UP_LOCATION VARCHAR2(100), 
	STORAGE_LOCATION VARCHAR2(100), 
	REALLOCATION_COST NUMBER, 
	CAPEX_DATE_SUBMITTED DATE, 
	CAPEX_SUBMITTED_BY VARCHAR2(100), 
	CAPEX_SERVICE_ID NUMBER, 
	CAPEX_DIVISION_ID NUMBER, 
	CAPEX_RC_CODE VARCHAR2(11), 
	CAPEX_DELIVERY_LOCATION_CODE VARCHAR2(500), 
	CAPEX_SERVICE_MANAGER_ID NUMBER, 
	CAPEX_BUSINESS_MANAGER_ID NUMBER, 
	CAPEX_BUDGET_HOLDER_ID NUMBER, 
	CAPEX_FINANCIAL_YEAR NUMBER, 
	CAPEX_BUDGET_TYPE_ID NUMBER, 
	CAPEX_BUDGET_COST NUMBER, 
	REQUISITION_NUMBER VARCHAR2(300), 
	PO_NUMBER VARCHAR2(300), 
	PURCHASE_DATE_RECEIVED DATE, 
	DISP_DATE_SUBMITTED DATE, 
	DISP_SUBMITTED_BY VARCHAR2(100), 
	DISP_PHONE VARCHAR2(100), 
	DISP_SERVICE_ID NUMBER, 
	DISP_DIVISION_ID NUMBER, 
	DISP_SERVICE_MANAGER_ID NUMBER, 
	DISP_RC_CODE VARCHAR2(11), 
	DISP_PICK_UP_SITE VARCHAR2(100), 
	DISP_TAKE_TO NUMBER, 
	DISP_DATE_BOOKED DATE, 
	DISP_ASSIGNED_TO NUMBER, 
	DISP_ITEMS_REUSE VARCHAR2(100), 
	DISP_BROKEN_DAMAGED VARCHAR2(100), 
	REAL_DATE_SUBMITTED DATE, 
	REAL_SUBMITTED_BY VARCHAR2(100), 
	REAL_PHONE VARCHAR2(30), 
	REAL_SERVICE_ID NUMBER, 
	REAL_DIVISION_ID NUMBER, 
	REAL_SERVICE_MANAGER_ID NUMBER, 
	REAL_RC_CODE VARCHAR2(11), 
	REAL_PICK_UP_FROM NUMBER, 
	REAL_TAKE_TO NUMBER, 
	REAL_DATE_BOOKED DATE, 
	REAL_ASSIGNED_TO NUMBER, 
	REAL_ITEM NUMBER, 
	REAL_QUANTITY NUMBER, 
	REAL_COST_AVOIDANCE NUMBER, 
	DISP_PICK_UP_BUILDING VARCHAR2(100), 
	DISP_PICK_UP_FLOOR VARCHAR2(100), 
	DISP_PICK_UP_ROOM VARCHAR2(100), 
	REAL_PICK_UP_BUILDING VARCHAR2(100), 
	REAL_PICK_UP_FLOOR VARCHAR2(100), 
	REAL_PICK_UP_ROOM VARCHAR2(100), 
	REAL_PICK_UP_SITE VARCHAR2(100), 
	APP_SIGNATURE_1 VARCHAR2(30), 
	APP_DATE_SENT_1 DATE, 
	APP_DATE_RECEIVED_1 DATE, 
	APP_SIGNATURE_2 VARCHAR2(30), 
	APP_DATE_SENT_2 DATE, 
	APP_DATE_RECEIVED_2 DATE, 
	APP_SIGNATURE_3 VARCHAR2(30), 
	APP_DATE_SENT_3 DATE, 
	APP_DATE_RECEIVED_3 DATE, 
	APP_SIGNATURE_4 VARCHAR2(30), 
	APP_DATE_SENT_4 DATE, 
	APP_DATE_RECEIVED_4 DATE, 
	APP_SIGNATURE_5 VARCHAR2(30), 
	APP_DATE_SENT_5 DATE, 
	APP_DATE_RECEIVED_5 DATE, 
	EXPECTED_DELIVERY_DATE DATE, 
	REAL_OTHER_LOCATION VARCHAR2(100), 
	DISP_OTHER_LOCATION VARCHAR2(100), 
	NEW_REPLACE VARCHAR2(10), 
	DISP_COMMENTS VARCHAR2(1000), 
	REAL_COMMENTS VARCHAR2(1000), 
	Y_NUMBER VARCHAR2(100), 
	ASSET_NUMBER VARCHAR2(100), 
	TS_DESCRIPTION VARCHAR2(100), 
	DATE_PURCHASED DATE, 
	SUPPLIER VARCHAR2(100), 
	TRADE_IN_VALUE NUMBER, 
	NBV NUMBER, 
	DDFS DATE, 
	DFSB VARCHAR2(100), 
	DSCA DATE, 
	DSSDF VARCHAR2(100), 
	DIG DATE, 
	DICNR DATE, 
	CAPEX_SUPPLIERS VARCHAR2(100), 
	CAPEX_QUOTE_EXPIRY DATE, 
	CAPEX_LEASE_PURCHASE VARCHAR2(1), 
    AD_DATE_SUBMITTED DATE, 
	AD_SUBMITTED_BY VARCHAR2(255), 
	AD_SUBMISSION_METHOD VARCHAR2(50), 
	AD_SERVICE_ID NUMBER, 
	AD_DISPOSAL_REASON VARCHAR2(100), 
	AD_SERIAL_NUMBER VARCHAR2(50), 
	AD_MAKE_MODEL VARCHAR2(100), 
	AD_PICK_UP_SITE VARCHAR2(100), 
	AD_PICK_UP_BUILDING VARCHAR2(100), 
	AD_PICK_UP_FLOOR VARCHAR2(100), 
	AD_PICK_UP_ROOM VARCHAR2(100), 
	AD_FIXED_ASSET VARCHAR2(100), 
	AD_DATE_PURCHASED DATE, 
	AD_RC_CODE VARCHAR2(100), 
	PURCHASE_RAN VARCHAR2(100), 	
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_MICROSITES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER NOT NULL ENABLE, 
	ROW_KEY VARCHAR2(30), 
	CONTENT_ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(255), 
	PUBLISH_YN VARCHAR2(1), 
	VIEW_ACL VARCHAR2(4000), 
	DISPLAY_SEQUENCE NUMBER, 
	WARNING_MESSAGE VARCHAR2(4000), 
	PRIMARY_TITLE VARCHAR2(255), 
	SUB_TITLE VARCHAR2(4000), 
	SHOW_TOC VARCHAR2(1), 
	TOC_LABEL VARCHAR2(255), 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_PROJ_MICROSITES_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_MICROSITES_VALID_HTML 
   (	ID NUMBER, 
	TAG_TYPE VARCHAR2(255) NOT NULL ENABLE, 
	TAGS VARCHAR2(4000) NOT NULL ENABLE, 
	TAG_RULE VARCHAR2(30), 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_PROJ_MICROS_V_HTML_RULE CHECK (tag_rule in ('allow','remove')) ENABLE, 
	 CONSTRAINT EBA_PROJ_MICROSITES_HTML_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_MICROSITE_CONTENT 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER NOT NULL ENABLE, 
	ROW_KEY VARCHAR2(30), 
	MICROSITE_ID NUMBER, 
	CONTENT_TYPE VARCHAR2(30), 
	SECTION_NAME VARCHAR2(255) NOT NULL ENABLE, 
	DISPLAY_SEQUENCE NUMBER, 
	PUBLISH_YN VARCHAR2(1), 
	ACL VARCHAR2(4000), 
	CONTENT CLOB, 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_PROJ_MICROSITE_CONTENT_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_MICROSITE_IMAGES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER NOT NULL ENABLE, 
	ROW_KEY VARCHAR2(30), 
	MICROSITE_ID NUMBER, 
	SHORT_NAME VARCHAR2(30), 
	SCALE_WIDTH NUMBER, 
	FILENAME VARCHAR2(4000), 
	FILE_MIMETYPE VARCHAR2(512), 
	FILE_CHARSET VARCHAR2(512), 
	FILE_BLOB BLOB, 
	FILE_COMMENTS VARCHAR2(4000), 
	CREATED_BY VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_PROJ_MICROSITE_IMAGES_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_PREFERENCES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	PREFERENCE_NAME VARCHAR2(100), 
	PREFERENCE_VALUE VARCHAR2(4000), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_REALLOCATION_ITEMS 
   (	REALLOC_ITEM_ID NUMBER NOT NULL ENABLE, 
	PROJ_STATUS_ID NUMBER NOT NULL ENABLE, 
	ITEM_ID NUMBER NOT NULL ENABLE, 
	QUANTITY NUMBER NOT NULL ENABLE, 
	COST_AVOIDANCE NUMBER NOT NULL ENABLE, 
	CREATED DATE, 
	CREATED_BY VARCHAR2(25), 
	UPDATED DATE, 
	UPDATED_BY VARCHAR2(25), 
	 CONSTRAINT REALLOC_ITEM PRIMARY KEY (REALLOC_ITEM_ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS1 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	CAT_ID NUMBER, 
	PARENT_PROJECT_ID NUMBER, 
	ROW_KEY VARCHAR2(30), 
	PROJECT VARCHAR2(200), 
	DESCRIPTION VARCHAR2(4000), 
	PROJECT_CUSTOMER VARCHAR2(255), 
	LOCKDOWN_TO_OWNERS_YN VARCHAR2(1), 
	PROJECT_OWNER VARCHAR2(255), 
	PROJECT_OWNER4 VARCHAR2(255), 
	PROJECT_OWNER11 VARCHAR2(255), 
	PROJECT_OWNER12 VARCHAR2(255), 
	OWNER_1_ROLE_ID NUMBER, 
	OWNER_2_ROLE_ID NUMBER, 
	OWNER_3_ROLE_ID NUMBER, 
	OWNER_4_ROLE_ID NUMBER, 
	OWNER_5_ROLE_ID NUMBER, 
	OWNER_6_ROLE_ID NUMBER, 
	OWNER_7_ROLE_ID NUMBER, 
	OWNER_8_ROLE_ID NUMBER, 
	OWNER_9_ROLE_ID NUMBER, 
	OWNER_10_ROLE_ID NUMBER, 
	OWNER_11_ROLE_ID NUMBER, 
	OWNER_12_ROLE_ID NUMBER, 
	PROJECT_FLEX_01 VARCHAR2(4000), 
	PROJECT_FLEX_02 VARCHAR2(4000), 
	PROJECT_FLEX_03 VARCHAR2(4000), 
	PROJECT_FLEX_04 VARCHAR2(4000), 
	PROJECT_FLEX_05 VARCHAR2(4000), 
	PROJECT_FLEX_06 VARCHAR2(4000), 
	PROJECT_FLEX_07 VARCHAR2(4000), 
	PROJECT_FLEX_08 VARCHAR2(4000), 
	PROJECT_FLEX_N01 NUMBER, 
	PROJECT_FLEX_N02 NUMBER, 
	PROJECT_FLEX_N03 NUMBER, 
	PROJECT_FLEX_N04 NUMBER, 
	PROJECT_FLEX_D01 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	PROJECT_FLEX_D02 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	PROJECT_FLEX_D03 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	PROJECT_FLEX_D04 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	PROJECT_FLEX_CLOB CLOB, 
	PROJECT_STATUS NUMBER, 
	TAGS VARCHAR2(4000), 
	NEXT_MILESTONE_NAME VARCHAR2(100), 
	NEXT_MILESTONE_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	GOAL VARCHAR2(4000), 
	WHAT_IS_SUCCESS VARCHAR2(4000), 
	URL VARCHAR2(4000), 
	INCLUDE_BY_DEFAULT_YN VARCHAR2(1), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	FINANCIAL_YEAR VARCHAR2(50), 
	BUDGETED_COST NUMBER, 
	APPROVED_COST NUMBER, 
	CER_NO_PROJECT_ID VARCHAR2(50), 
	AC_APPROVAL_DATE DATE, 
	AVOIDANCE_COST NUMBER, 
	PICK_UP_LOCATION VARCHAR2(100), 
	STORAGE_LOCATION VARCHAR2(100), 
	REALLOCATION_COST NUMBER
   )
/
CREATE TABLE  EBA_PROJ_STATUS_ACCESS_LEVELS 
   (	ID NUMBER NOT NULL ENABLE, 
	ACCESS_LEVEL VARCHAR2(30) NOT NULL ENABLE, 
	ROW_VERSION NUMBER, 
	 CONSTRAINT EBA_PROJ_STAT_ACC_LVL_CK CHECK (access_level in (
        'Administrator',
        'Contributor',
        'Reader' )) ENABLE, 
	 CONSTRAINT EBA_PROJ_STAT_ACCESS_LEVELS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_AIS_TYPES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	AI_TYPE VARCHAR2(50) NOT NULL ENABLE, 
	DISPLAY_SEQUENCE NUMBER, 
	IS_ACTIVE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_AIS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	ROW_KEY VARCHAR2(30), 
	PROJECT_ID NUMBER, 
	MILESTONE_ID NUMBER, 
	ACTION_OWNER_01 VARCHAR2(255), 
	ACTION_OWNER_02 VARCHAR2(255), 
	ACTION_OWNER_03 VARCHAR2(255), 
	ACTION_OWNER_04 VARCHAR2(255), 
	ACTION VARCHAR2(255), 
	ACTION_DESCRIPTION CLOB, 
	DUE_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	ACTION_STATUS VARCHAR2(30), 
	IS_DELIVERABLE_YN VARCHAR2(1), 
	TYPE_ID NUMBER, 
	TAGS VARCHAR2(4000), 
	ACTION_FLEX_01 VARCHAR2(4000), 
	ACTION_FLEX_02 VARCHAR2(4000), 
	ACTION_FLEX_03 VARCHAR2(4000), 
	ACTION_FLEX_04 VARCHAR2(4000), 
	ACTION_FLEX_05 VARCHAR2(4000), 
	ACTION_FLEX_06 VARCHAR2(4000), 
	ACTION_FLEX_07 VARCHAR2(4000), 
	ACTION_FLEX_08 VARCHAR2(4000), 
	ACTION_FLEX_N01 NUMBER, 
	ACTION_FLEX_N02 NUMBER, 
	ACTION_FLEX_N03 NUMBER, 
	ACTION_FLEX_N04 NUMBER, 
	ACTION_FLEX_D01 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	ACTION_FLEX_D02 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	ACTION_FLEX_D03 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	ACTION_FLEX_D04 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	ACTION_FLEX_CLOB CLOB, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_AI_CMNTS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	ACTION_ITEM_ID NUMBER, 
	COMMENT_TEXT CLOB, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_CLICKS 
   (	ID NUMBER, 
	PROJECT_ID NUMBER, 
	APP_USERNAME VARCHAR2(255), 
	VIEW_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	APP_SESSION VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_EMAIL_REQ 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	PROJECT_ID NUMBER, 
	EMAIL_FIRST_TO VARCHAR2(255), 
	EMAIL_TO VARCHAR2(4000), 
	EMAIL_FROM VARCHAR2(255), 
	EMAIL_SUBJECT VARCHAR2(255), 
	EMAIL_TEXT_BODY VARCHAR2(4000), 
	PROJ_ROW_VERSION_NUMBER NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_END 
   (	ID NUMBER, 
	STATUS_ID NUMBER, 
	ENDORSEMENT_ID NUMBER, 
	DATE_REQUESTED DATE, 
	ENDORSED_BY VARCHAR2(50), 
	DATE_ENDORSED DATE, 
	ENDORSEMENT_REQUIRED VARCHAR2(1), 
	FOLLOWUP_DATE DATE,
	 CONSTRAINT EBA_PROJECT_STATUS_END_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_END_BK 
   (	ID NUMBER, 
	STATUS_ID NUMBER, 
	ENDORSEMENT_ID NUMBER, 
	DATE_REQUESTED DATE, 
	ENDORSED_BY VARCHAR2(50), 
	DATE_ENDORSED DATE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_FAVORITES 
   (	ID NUMBER, 
	USER_NAME VARCHAR2(255) NOT NULL ENABLE, 
	CONTENT_ID NUMBER NOT NULL ENABLE, 
	CONTENT_TYPE VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT EBA_PROJ_STATUS_FAV_CK CHECK (content_type in ('PROJECT','ACTION ITEM')) ENABLE, 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_FILES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	PROJECT_ID NUMBER, 
	FILENAME VARCHAR2(4000), 
	FILE_MIMETYPE VARCHAR2(512), 
	FILE_CHARSET VARCHAR2(512), 
	FILE_BLOB BLOB, 
	FILE_COMMENTS VARCHAR2(4000), 
	TAGS VARCHAR2(4000), 
	ASSOCIATED_MILESTONE NUMBER, 
	ASSOCIATED_ACTION_ITEM NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_INGEST_LOG 
   (	ID NUMBER, 
	P_TO VARCHAR2(4000), 
	P_FROM VARCHAR2(4000), 
	P_CC VARCHAR2(4000), 
	P_SUBJECT VARCHAR2(4000), 
	P_BODY VARCHAR2(4000), 
	APPLY_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	ROWS_PROCESSED NUMBER, 
	ROW_KEY VARCHAR2(255), 
	COMPONENT_ID NUMBER, 
	LOG_INFO VARCHAR2(4000), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_LINKS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	PROJECT_ID NUMBER, 
	LINK_TARGET VARCHAR2(4000), 
	LINK_TEXT VARCHAR2(255), 
	LINK_COMMENTS VARCHAR2(4000), 
	INCLUDE_BY_DEFAULT_YN VARCHAR2(1), 
	TAGS VARCHAR2(4000), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_MS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	ROW_KEY VARCHAR2(30), 
	PROJECT_ID NUMBER, 
	MILESTONE_NAME VARCHAR2(255), 
	MILESTONE_DESCRIPTION VARCHAR2(4000), 
	MILESTONE_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	MILESTONE_START_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	MILESTONE_STATUS VARCHAR2(30), 
	MILESTONE_OWNER VARCHAR2(255), 
	IS_MAJOR_YN VARCHAR2(1), 
	TAGS VARCHAR2(4000), 
	MILESTONE_FLEX_01 VARCHAR2(4000), 
	MILESTONE_FLEX_02 VARCHAR2(4000), 
	MILESTONE_FLEX_03 VARCHAR2(4000), 
	MILESTONE_FLEX_04 VARCHAR2(4000), 
	MILESTONE_FLEX_05 VARCHAR2(4000), 
	MILESTONE_FLEX_06 VARCHAR2(4000), 
	MILESTONE_FLEX_07 VARCHAR2(4000), 
	MILESTONE_FLEX_08 VARCHAR2(4000), 
	MILESTONE_FLEX_N01 NUMBER, 
	MILESTONE_FLEX_N02 NUMBER, 
	MILESTONE_FLEX_N03 NUMBER, 
	MILESTONE_FLEX_N04 NUMBER, 
	MILESTONE_FLEX_D01 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	MILESTONE_FLEX_D02 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	MILESTONE_FLEX_D03 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	MILESTONE_FLEX_D04 TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	MILESTONE_FLEX_CLOB CLOB, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_NOTIFICATIONS 
   (	ID NUMBER NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER, 
	NOTIFICATION_NAME VARCHAR2(255) NOT NULL ENABLE, 
	NOTIFICATION_DESCRIPTION VARCHAR2(4000), 
	NOTIFICATION_TYPE VARCHAR2(30) NOT NULL ENABLE, 
	DISPLAY_SEQUENCE NUMBER, 
	DISPLAY_FROM TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	DISPLAY_UNTIL TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255) NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255) NOT NULL ENABLE, 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT EBA_PROJ_STATUS_NOTE_TP_CC CHECK (notification_type in ('RED','YELLOW')) ENABLE, 
	 CONSTRAINT EBA_PROJ_STATUS_NOTE_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_REPORTS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	REPORT_NAME VARCHAR2(255), 
	REPORT_DESCRIPTION CLOB, 
	ROW_KEY VARCHAR2(50), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_RPTS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	ROW_KEY VARCHAR2(30), 
	PROJECT_ID NUMBER NOT NULL ENABLE, 
	STATUS_TITLE VARCHAR2(255) NOT NULL ENABLE, 
	STATUS_UPDATE CLOB, 
	UPDATE_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	UPDATE_OWNER VARCHAR2(255) NOT NULL ENABLE, 
	VIEWABLE_BY VARCHAR2(255) NOT NULL ENABLE, 
	EDITABLE_BY VARCHAR2(255) NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_RPT_PROJ_UPD 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	UPDATE_ID NUMBER, 
	REPORT_ID NUMBER, 
	PROJECT_ID NUMBER NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_SEARCHES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	SEARCH_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	SEARCH_STRING VARCHAR2(4000), 
	SEARCH_USER VARCHAR2(255), 
	HITS NUMBER, 
	PARMS VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_UPDATE_TYPES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	STATUS_UPDATE_TYPE VARCHAR2(255) NOT NULL ENABLE, 
	IS_ACTIVE_YN VARCHAR2(1), 
	DISPLAY_SEQUENCE NUMBER, 
	TYPE_SHORT_DESC VARCHAR2(255), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE, 
	 UNIQUE (STATUS_UPDATE_TYPE)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_UPDATES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	ROW_KEY VARCHAR2(30), 
	PROJECT_ID NUMBER, 
	STATUS_UPDATE CLOB, 
	UPDATE_DATE TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATE_OWNER VARCHAR2(255), 
	INCLUDE_ON_STATUS_RPT VARCHAR2(1), 
	CLASSIFICATION_ID NUMBER, 
	UPDATE_TYPE NUMBER, 
	TAGS VARCHAR2(4000), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_UPD_CLASSES 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	CLASSIFICATION VARCHAR2(255), 
	CLASSIFICATION_DESCRIPTION VARCHAR2(4000), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_USERS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	USERNAME VARCHAR2(255) NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	ACCESS_LEVEL_ID NUMBER, 
	ACCOUNT_LOCKED VARCHAR2(1), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE, 
	 UNIQUE (USERNAME)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_STATUS_VERIFICATIONS 
   (	ID NUMBER, 
	PROJECT_ID NUMBER, 
	VERIFIED_BY VARCHAR2(255) NOT NULL ENABLE, 
	VERIFICATION_COMMENT VARCHAR2(4000), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_TAGS 
   (	ID NUMBER, 
	ROW_VERSION_NUMBER NUMBER, 
	TAG VARCHAR2(255) NOT NULL ENABLE, 
	CONTENT_ID NUMBER, 
	CONTENT_TYPE VARCHAR2(30), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE, 
	 CONSTRAINT EBA_PROJ_TAGS_CK CHECK (content_type in ('STATUS','FILE','AI','MILESTONE','LINK','UPDATES')) ENABLE
   )
/
CREATE TABLE  EBA_PROJ_TAGS_SUM 
   (	TAG VARCHAR2(255), 
	TAG_COUNT NUMBER, 
	 CONSTRAINT EBA_PROJ_TAGS_SUM_PK PRIMARY KEY (TAG)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_TAGS_TYPE_SUM 
   (	TAG VARCHAR2(255), 
	CONTENT_TYPE VARCHAR2(30), 
	TAG_COUNT NUMBER, 
	 CONSTRAINT EBA_PROJ_TAGS_TP_SUM_PK PRIMARY KEY (TAG, CONTENT_TYPE)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_TZ_PREF 
   (	ID NUMBER NOT NULL ENABLE, 
	USERNAME VARCHAR2(255) NOT NULL ENABLE, 
	TIMEZONE_PREFERENCE VARCHAR2(255) NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER NOT NULL ENABLE, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	CREATED_BY VARCHAR2(255) NOT NULL ENABLE, 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	UPDATED_BY VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT EBA_PROJ_TZ_PREF_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE, 
	 CONSTRAINT EBA_PROJ_TZ_PREF_UK UNIQUE (USERNAME)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_PROJ_USER_PREFERENCES 
   (	ID NUMBER, 
	USERNAME VARCHAR2(255) NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER, 
	PREFERENCE_NAME VARCHAR2(100) NOT NULL ENABLE, 
	PREFERENCE_VALUE VARCHAR2(4000), 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_SERVICE 
   (	SERVICE_ID NUMBER, 
	DESCRIPTION VARCHAR2(100), 
	 CONSTRAINT EBA_SERVICE_PK PRIMARY KEY (SERVICE_ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_UT_CHART_PROJECTS 
   (	ID NUMBER NOT NULL ENABLE, 
	PROJECT VARCHAR2(30) NOT NULL ENABLE, 
	ROW_VERSION_NUMBER NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_UT_CHARTS_PROJ_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
CREATE TABLE  EBA_UT_CHART_TASKS 
   (	ID NUMBER NOT NULL ENABLE, 
	PROJECT NUMBER, 
	PARENT_TASK NUMBER, 
	TASK_NAME VARCHAR2(255), 
	ROW_VERSION_NUMBER NUMBER, 
	START_DATE DATE, 
	END_DATE DATE, 
	STATUS VARCHAR2(30), 
	ASSIGNED_TO VARCHAR2(30), 
	COST NUMBER, 
	BUDGET NUMBER, 
	CREATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	CREATED_BY VARCHAR2(255), 
	UPDATED TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	UPDATED_BY VARCHAR2(255), 
	 CONSTRAINT EBA_UT_CHART_TASKS_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   )
/
